# Configuration file for `pre-commit` (https://pre-commit.com/)

# To use pre-commit, first install globally with `pip install pre-commit`
# To install and activate the hooks, use `pre-commit install`
# By default, pre-commit only runs on modified files
# To run on all files, use `pre-commit run --all-files`

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: debug-statements
          - id: requirements-txt-fixer
          - id: trailing-whitespace
          - id: check-json
          - id: check-yaml
          - id: check-toml

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.263
      hooks:
          - id: ruff

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.2.0
      hooks:
          - id: mypy

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint
