[tool.mypy]
# mypy configuration: https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
disable_error_code = ["union-attr", "return"]
disallow_untyped_decorators = false
explicit_package_bases = true
namespace_packages = true
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.ruff]
# Ignore ambiguous variable name
ignore = ["E741"]
# Enable Pyflakes and pycodestyle rules
line-length = 120
select = ["E", "F"]

[tool.bandit]
skips = ["B101"]
